### ISSUE TITLE
Create with options fails

### ISSUE THREAD

**Issue by abstracthat** [EventedMind/em#70]
It's a minor issue since it's easy enough to meteor create, cd, rm default files, and em init with the options.

```
em g:create auto --ir --css=stylus --js=coffee --html=jade
```

returns...

```
Looks like you're not in a Meteor project directory.
Installing the package iron:router... \

/usr/local/lib/node_modules/meteor-em/lib/command.js:276
        self.logError("Error installing package " + package + ". " + String(er
        ^
ReferenceError: self is not defined
    at /usr/local/lib/node_modules/meteor-em/lib/command.js:276:9
    at ChildProcess.exithandler (child_process.js:652:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

**Comment by scott-mcpherson** [comment]
Can you guys please give the latest release a try when you get a chance.
You should be able to use the create command now with the following syntax:

```sh
$ em create auto --ir --css=stylus --js=coffee --html=jade
```

**Comment by abstracthat** [comment]
Thanks! It works but it would be nice if it also installed coffeescript, stylus, and mquandalle:jade packages.

**Comment by scott-mcpherson** [comment]
Yeah, I agree. I think with the next release we'll probably add a global config file that'll enable developers to set some default packages to install.
